config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  use_doorkeeper

  resources :actions do
    member do
      get :execute
    end
  end

  root 'actions#index'

end

app/models/action.rb
class Action < ActiveRecord::Base
  validates :name, :implementation, presence: true
  validates :default_time, numericality: {allow_blank: true, greater_than_or_equal_to: 500, less_than_or_equal_to: 10000}
  validates :port, numericality: {allow_blank: true, greater_than: 0, less_than_or_equal_to: 65536}
  validates :api_key, length: {maximum: 100}
  validate :check_whitespace


private
  def check_whitespace
    if self.host.match(/\s+/)
      errors.add(:host, "Whitespace not allowed")
    end
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  before_action :set_action, only: [:show, :edit, :update, :destroy, :unlock]
  #before_action :doorkeeper_authorize!, only: :unlock

  respond_to :html, :json

  def index
    @actions = Action.all
    respond_with(@action)
  end

  def show
    respond_with(@action)
  end

  def new
    @action = Action.new
    respond_with(@action)
  end

  def edit
  end

  def create
    @action = Action.new(action_params)
    @action.save
    respond_with(@action)
  end

  def update
    @action.update(action_params)
    respond_with(@action)
  end

  def destroy
    @action.destroy
    respond_with(@action)
  end

  def execute
    # Send the unlock command.
    # TODO: send the unlock command ;)
    @response = true, "OK"
    respond_with(@action)
  end

  private
    def set_action
      @action = Action.find(params[:id])
    end

    def action_params
      params.require(:a).permit(:name, :description, :activated, :implementation, :api_key, :default_time, :host, :port)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_admin!
end

app/helpers/actions_helper.rb
module ActionsHelper
  def checkbox_icon activated
    unless activated
      return fa_icon 'square-o'
    end
    fa_icon 'check-square-o'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doorbuzzers_helper.rb
module DoorbuzzersHelper
  def checkbox_icon activated
    unless activated
      return fa_icon 'square-o'
    end
    fa_icon 'check-square-o'
  end
end

app/views/actions/_form.html.slim
= simple_form_for @action, as: :a, html: { class: "form form-horizontal action" } do |f|
  = f.input :name
  = f.input :description
  = f.input :activated, input_html: { value: '1' }
  = f.input :implementation, collection: BaseAction.descendants, include_blank: false
  = f.input :api_key, placeholder: 'The API-key of the action'
  = f.input :default_time, placeholder: 'How long to apply action (in milliseconds) (if applicable)', input_html: {min: 500, step: 500, max: 10000}
  = f.input :host, placeholder: 'Hostname or IP-address'
  = f.input :port, placeholder: 'Port number', input_html: {min: 1, max: 65536}
  = f.button :submit, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), actions_path, :class => 'btn'

app/views/actions/edit.html.slim
- model_class = Action
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/actions/execute.html.slim
-if @response[0]
  h3 The action has been executed
-else
  h3 Something went wrong
blockquote
  => @action.name
  'responded with
  = @response[1]

= link_to 'Back', :back, :class => 'btn'

app/views/actions/index.html.slim
- model_class = Action
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:description)
      th= model_class.human_attribute_name(:activated)
      th= model_class.human_attribute_name(:default_time)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @actions.each do |action|
      tr
        td= link_to action.name, action_path(action)
        td= action.description
        td= checkbox_icon action.activated
        td= action.default_time
        td
          = link_to execute_action_path(action), class: 'btn btn-default btn-xs' do fa_icon 'arrow-circle-o-right', text: 'Execute' end
          '
          = link_to edit_action_path(action), class: 'btn btn-default btn-xs' do fa_icon 'pencil', text: 'Edit' end
          '
          = link_to action_path(action), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' do fa_icon 'trash', text: 'Delete' end

= link_to new_action_path, class: 'btn btn-primary' do fa_icon 'plus', text: 'New' end

app/views/actions/new.html.slim
- model_class = Action
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/actions/show.html.slim
- model_class = Action
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @action.name
p
  strong= model_class.human_attribute_name(:description) + ':'
  br
  = @action.description
p
  strong= model_class.human_attribute_name(:activated) + ':'
  br
  = @action.activated
p
  strong= model_class.human_attribute_name(:implementation) + ':'
  br
  = @action.implementation
p
  strong= model_class.human_attribute_name(:api_key) + ':'
  br
  = @action.api_key
p
  strong= model_class.human_attribute_name(:default_time) + ':'
  br
  = @action.default_time
p
  strong= model_class.human_attribute_name(:host) + ':'
  br
  = @action.host
p
  strong= model_class.human_attribute_name(:port) + ':'
  br
  = @action.port

= link_to t('.back', :default => t("helpers.links.back")), actions_path, :class => 'btn btn-default'
'
= link_to edit_action_path(@action), :class => 'btn btn-default' do fa_icon 'pencil', text: "Edit" end
'
= link_to action_path(@action), :method => "delete", :data => { confirm: 'Are you sure?'}, class: 'btn btn-danger' do fa_icon 'trash', text: 'Delete' end
'
= link_to execute_action_path(@action), class: 'btn btn-default' do fa_icon 'arrow-circle-o-right', text: 'Execute' end

app/views/doorbuzzers/edit.html.slim
- model_class = Doorbuzzer
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/doorbuzzers/new.html.slim
- model_class = Doorbuzzer
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/doorbuzzers/unlock.html.slim
-if @response[0]
  h3 The door has been unlocked
-else
  h3 Something went wrong
blockquote
  => @doorbuzzer.name
  'responded with
  = @response[1]

= link_to 'Back', :back, :class => 'btn'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Action Server"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/" ActionServer
          - if admin_signed_in?
            .navbar-collapse.collapse.navbar-responsive-collapse
              ul.nav.navbar-nav
                li= link_to 'OAuth', oauth_applications_path
              ul.nav.navbar-nav.navbar-right
                li = link_to destroy_admin_session_path, method: :delete do fa_icon 'sign-out', text: 'Sign out' end
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        /.col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      footer
        hr
        p &copy; Emil Edholm 2015